collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.07021277
color:
  saturation: 0.5702128
  brandStrength: 0.1533967850264162
  lightness: 0.3106383
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
  rhythmicContrast: 0.6042553
layout_spectrum: 0.1446809
name: Apptitudde
